### PR TITLE
Vic 20 dithering support added (preliminary)

### PR DESCRIPTION
**Pull request by robin-raymond**
Vic 20 dithering support added (preliminary)

The Vic 20 has some unique attributes that are similar but different
than the Commodore 64. The Vic 20 doesn't have a true graphics
mode but instead relies on character re-imaging and color choices
to make a pseudo bitmap. Combined with the Vic 20's flexible
screen sizes, this makes an interesting target.

Some key differences added:
- In multi mode, the Vic 20 has the choice of 4 color options
just like the C64, except three of the choices are the background,
border, and auxiliary color. These are global colors, and then
each block gets the choice of its own foreground color.
- In hires mode, the choice is the background or a foreground
color for the block
- In multi-mode the palette is fully available for the background,
and aux color but a palette subset is used for the aux color and
the foreground color.
- In hires mode, the palette is restricted for the background and
the foreground color.

Code changes (some refactoring):
- The global color selection is improved, because the choice
of global colors is so critical for the vic, the background, aux,
and border colors are selected by pixels, whereas commodore 64
only uses the background (at times), the logic now first uses
histogram usage to pick the top N colors based on usage if the
color is useable by the image's pixels. The remaining colors
that are needed to have compatible colors are based on the
intensity and are selected for palette compatibility to the
image rather than overall usage.
- the palette options got a lot more complex in the settings
so those got split out into their own dithering settings with
appropriate defaults that would mean the rest of the settings
don't need to specify anything and they will still work
- the pixel color choices now respect the palette subset that
can happen in the case of the Vic 20
- added VIC 20 palette colors (there are some differences between
systems but this is true of the C64 as well)
- added export bin routines for the Vic 20 which are likely to
produce nothing much of useful value given they aren't tested
against working code
- misc typos and a few inconsistencies in the code (code could use
a good auto-format tool as I find the editors liking to do it
the way they think the code should be not how the code is)

### CODE REVIEW

**Comment by robin-raymond** [comment]
Related to issue https://github.com/sehugg/dithertron/issues/18

**Comment by sehugg** [comment]
VIC-20! It's getting serious now! :) This ought to be cool.

BTW, it might take me a little while to merge because I'm refactoring into proper TypeScript modules, so some files will be moved around. But it should be a little more manageable, and no major API changes.

**Comment by robin-raymond** [comment]
Oh yes! This is an up-and-coming platform, I just know it! In all seriousness, the Vic 20 needs some love. I couldn't let this platform be neglected with such a useful tool given I knew most of the Commodore code would be able to also handle the Vic 20 with small tweaks. Then I discovered Vic 20's 10-color choice graphics ;-). See images below for a sneak peak!

Understood about the merge. Since I am not a typescript expert, I'll leave that up to you because I honestly don't know what is "proper".

vic-20-multi
vic-20-hires

**Comment by robin-raymond** [comment]
BTW, the display on the UI that says "WWW x HHH, N colors, WxH" probably needs an asterisk when it comes to the Vic-20! While the Vic technically has 16 colors, the actual palette gets restricted to 8 for some of the colors (depending on context) despite the wider palette being present. It's a bit a bit weird but you can tell the Commodore engineers were trying to squeeze every bit of power out of that machine despite its cost reduce form.

**Comment by sehugg** [comment]
Wow that looks great! I agree the VIC-20 needs a little love, I hope i can get the emulator working one day, at least with cartridges.

I pushed the Typescript refactoring, and I'm pretty sure it broke the PR, sorry. Don't want to break your momentum. The files are reorganized, but you ought to be able to cut-and-paste your changes and add a few exports and imports here and there. I did find a way to bundle the .asm files as plain text files, so that's nice. Let me know if you need help with the new structure.

**Comment by robin-raymond** [comment]
Wonderful news! I'll sync the code up and fix the PR in the coming day(s).

**Comment by robin-raymond** [comment]
Replacement PR is up. You may reject this one.

**Pull request closed without merging**
