### PR TITLE
Added dithering of SNES

### PR DESCRIPTION
**Pull request by robin-raymond**
This adds 32x32 grid of 2bpp to 8bpp as well as direct color modes for
the SNES. This does not allow exporting of the data but it's a first
step towards that goal. SNES is considered experimental and untested
if the result is usable in the real world (although it is coded to be
proper).

Changes to the code:
- added SNES modes
- added SNES direct color mode
- refactored the export code to be more generic
- fixed sync bug between canvas and indexed
- added full palette mode to block canvas
- fixed vic20 fill choice (to not default to background)
- fixed vic20 to not sort the colors of two choices, but to instead
pick the top color only
- indexed needs to support > 256 values (SNES has 11 bit colors)
- made range routine faster by pre-allocating array

Fixes:
https://github.com/sehugg/dithertron/issues/33

Updates:
https://github.com/sehugg/dithertron/issues/32
https://github.com/sehugg/dithertron/issues/29
https://github.com/sehugg/dithertron/issues/18

Related:
https://github.com/sehugg/dithertron/issues/8

This addresses the issues (hopefully) with this PR:
https://github.com/sehugg/dithertron/pull/30

As this PR builds upon the previous PR (https://github.com/sehugg/dithertron/pull/30), this PR should be considered and the other PR can be ignored/rejected.

### CODE REVIEW

**Comment by robin-raymond** [comment]
@sehugg Do you have any insights into this one: expired: test/unit/test-c64.ts ? When I try them manually they work okay. The Vic20 was a legit issue, well, kind-of. The choice of default fill color I would not have expected to have as much impact on the result as it did, but otherwise this addresses that concern.

**Comment by sehugg** [comment]
For the VIC-20 hires it looks fine the web UI, but the output from the unit test is showing the wrong colors:
vic20 hires-1
Maybe something to do with the commit() order? The test runner just calls `iterate()` until it's finished and then grabs the data from `dithcanvas.img`, is that still valid?

For the C-64 it looks like the tests are timing out; some of them are taking more than 30 seconds to complete, whereas they all completed in under 10 seconds previously. Based on a quick profile run it seems it's spending a lot of time in `addToHistogramAtOffsetFrom`.

A lot has changed in this PR so I'm still getting my head around it, sorry to not be of more help.

**Comment by robin-raymond** [comment]
vic-20-hires

This is what I see. Doesn't what is presented on the screen have to match the iterate result? The commit order should not cause this issue, because update finalizes the img value based on the RGB of the indexed palette, which should match what is seen, no? If anything it should improve any issues of a mismatch.

I'm puzzled by that one.

As for the c64, I cannot reproduce the issue within the UI. I'm a bit unfamiliar with how to log within the unit test to debug what is being seen there (not a TS programmer by day). I think the `addToHistogramAtOffsetFrom` is a bit of a red herring. That would be called in any loop that would be updating the pixels from the `alt` values. This is just a version of your `histo` algorithm.

**Comment by sehugg** [comment]
I'm puzzled, too. I'll take a closer look. Weird that the palette issue only shows up on the vic20.hires test.

The performance issue is weird too. It doesn't look like the browser is affected. Maybe I'll try a different test framework.

**Comment by robin-raymond** [comment]
FYI: Added SNES export (experimental)

The various SNES modes (and by proxy NES and other systems) have been
added as binary export. These exports are untested in any imported
project but have been coded to be correct but bugs / misunderstandings
of the format may exist.

Changes to the code:
- added a bunch of new systems related to the SNES format
- added SNES 32x32, 32x64, 64x32, 64x64 support (although no systems
export these higher tilesets)
- added direct color mode / export BGR555
- made interfaces not optional and used Partial templating instead
- added feature to pre-fill canvas based on reference image instead of
dithering towards the reference image
- improved block export to support other styles of export
(e.g. bitplane)
- added SNES cell, tileset and palette exports for various SNES modes

**Comment by sehugg** [comment]
I found the source of the test slowdown. It was just `console.assert()`! Apparently it acquires a global lock or something, and it is very slow on web workers. It's probably a good idea to move these to a simple assert() function that just throws an exception on false.

**Comment by robin-raymond** [comment]
I can't do that yet because of this issue:
https://github.com/sehugg/dithertron/issues/15

If I change to a throw then this will cause asserts to happen and thus will throw exceptions until this bug is fixed (under normal usages). Is there anyway to detect browser vs non browser and thus I could map the assert appropriately?

**Comment by sehugg** [comment]
I think it's fine to keep logging the assertion failures, as long as we avoid `console.assert` and use our own function. It does seem to affect the browser too. I was very surprised! But it's there: https://jsperf.app/luruni/2

**Comment by robin-raymond** [comment]
I added a wrapper to only call console.assert during the failure condition. I'm not sure how to get the proper backtrace but at least the assert still happens (only when a failure condition happens and that should not happen under unit tests). I don't understand what the unit tests are complaining about though now.

**Comment by sehugg** [comment]
I think the VIC-20 test is failing because it's now limited to the first 8 colors, is that correct? If so I can tweak the test.

The ZX test is failing b/c it seems it likes to oscillate between states more than the rest. I can increase the rate of error threshold and reduce it somewhat.

**Comment by robin-raymond** [comment]
@sehugg Interesting. Yes, it's restricted to first 8 colors only, but some of the common colors are allowed to be 0-15, in some modes. But the common color is common for the entire display so it's not the best color for many pixels. It's complicated. The new routine reflects that complication. Curious, how does the test work? Does it compare against a previous example known output or does it calculate what it expects to be the output itself, then compare? In the case of the VIC, when I first started, the complexities of the VIC's restrictions were not coded fully so if a sample was captured at that point then yes, the colors would be more restricted now than previously.

As for the Zx, it does if there's some pixel blocks that are on the threshold of being within the light/dark mode threshold. This causes the oscillation because the error dips above/below this threshold since the dark is too dark but the light mode is too light (and the choice of dark or light is entirely mutually exclusive within the block so it can't just settle on a happy medium of partly dark and partly light). That's the consequence of allowing for light/dark mode. It wouldn't oscillate previously because it was always stuck exclusively in one mode only.

**Comment by sehugg** [comment]
The tests just downsample the source image and dithered image to low resolution and compare the average color distances to a threshold -- so it really just detects large regressions of quality. So before when VIC-20 was using the upper 8 colors it looked like [this](https://8bitworkshop.com/dithertron/#sys=vic20.hires&image=keyssunset.jpg) and now it looks like the images above. Which is fine if it is modeling the VIC-20 constraints accurately, I'll just adjust the test. (the hi-res mode only has lower 8 colors, right?)

**Comment by robin-raymond** [comment]
@sehugg Both have restrictions for Vic20. If you look at the min/max, you'll see color choices are indeed low palette with the high palette being accessible only for some global colors (for both hires and multi mode):

````ts
    {
        id: 'vic20.hires',
        name: 'VIC-20 Hires',
        width: 160,
        height: 160,
        scaleX: 1.5,
        conv: 'VICII_Canvas',
        pal: palettes.VIC20_PAL_RGB,
        block: { w: 8, h: 8, colors: 2 },               // can choose the background, or one foreground color
        cell: {w: 8, h: 8, msbToLsb: true },
        paletteChoices: {
            background: true,                           // pixels can choose the background color
            backgroundRange: { min: 0, max: 7 },        // (but with a reduced color palette)
            colorsRange: { min: 0, max: 7 }             // pixels can only choose from a reduced color palette
        },
        toNative:'exportVicHires',
    },
    {
        id: 'vic20.multi',
        name: 'VIC-20 Multi',
        width: 80,
        height: 160,
        scaleX: 3,
        conv: 'VICII_Canvas',
        pal: palettes.VIC20_PAL_RGB,
        block: { w: 4, h: 8, colors: 4 },               // can choose background, aux, border and one foreground color
        cell: {w: 4, h: 8, msbToLsb: true },    
        paletteChoices: {
            background: true,                           // pixels can choose the background color
            backgroundRange: { min: 0, max: 15 },
            aux: true,                                  // pixels can choose the aux color
            auxRange: { min: 0, max: 15},
            border: true,                               // pixels can choose the border color
            borderRange: { min: 0, max: 7 },            // (but with a reduced palette)
            colorsRange: { min: 0, max: 7 }             // a reduced palette applies to the pixel colors
        },
        toNative:'exportVicMulti',
    },
````

**Pull request merged**
